substitutions:
  _GEMINI_API_KEY: "AIzaSyDJEnINiuvI0SULRTqb5O1xgDYUZu_NwQo"
  _UNSPLASH_ACCESS_KEY: "a9d7ec28753fe782f2e898e09a774c13ce95a31e4262a7a685b7de02ee109524"
  _UNSPLASH_SECRET_KEY: "d19e1e9565e3e978b8cfee00d287e86612e01a58dabefcccd96039792046b885"
  _NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyAn0GcjLNGVXWAj8hAdS432wY2vuIlI8pA"
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "reeled-ai-48459.firebaseapp.com"
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: "reeled-ai-48459"
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "reeled-ai-48459.firebasestorage.app"
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "226878220430"
  _NEXT_PUBLIC_FIREBASE_APP_ID: "1:226878220430:web:f494f3b752303679c281df"
  _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "G-B00XCN63QD" 