steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/reeled-ai-production/reeled-ai-repo/reeled-ai-v2', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/reeled-ai-production/reeled-ai-repo/reeled-ai-v2']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'reeled-ai-v2'
      - '--image'
      - 'us-central1-docker.pkg.dev/reeled-ai-production/reeled-ai-repo/reeled-ai-v2'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--set-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'us-central1-docker.pkg.dev/reeled-ai-production/reeled-ai-repo/reeled-ai-v2'

timeout: 1800s











