#!/bin/bash
# Namecheap DNS Setup Script for reeledai.com

echo "🌐 Namecheap DNS Configuration for reeledai.com"
echo "=============================================="
echo ""
echo "✅ Domain mappings created in Google Cloud:"
echo "   • app.reeledai.com (already working)"
echo "   • www.reeledai.com (needs DNS)"
echo "   • reeledai.com (needs DNS)"
echo ""
echo "📋 DNS Records to Add in Namecheap:"
echo "=================================="
echo ""
echo "1. Log into Namecheap → Domain List → Manage → Advanced DNS"
echo ""
echo "2. Add these DNS records:"
echo ""
echo "   FOR www.reeledai.com:"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Type: CNAME                             │"
echo "   │ Host: www                              │"
echo "   │ Value: ghs.googlehosted.com           │"
echo "   │ TTL: 300                               │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "   FOR reeledai.com (root domain):"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Type: A                                 │"
echo "   │ Host: @                                 │"
echo "   │ Value: 216.239.32.21                   │"
echo "   │ TTL: 300                               │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Type: A                                 │"
echo "   │ Host: @                                 │"
echo "   │ Value: 216.239.34.21                   │"
echo "   │ TTL: 300                               │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Type: A                                 │"
echo "   │ Host: @                                 │"
echo "   │ Value: 216.239.36.21                   │"
echo "   │ TTL: 300                               │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "   ┌─────────────────────────────────────────┐"
echo "   │ Type: A                                 │"
echo "   │ Host: @                                 │"
echo "   │ Value: 216.239.38.21                   │"
echo "   │ TTL: 300                               │"
echo "   └─────────────────────────────────────────┘"
echo ""
echo "⏰ After adding DNS records:"
echo "   • DNS propagation: 24-48 hours"
echo "   • SSL certificates: Auto-provisioned by Google"
echo ""
echo "🌐 Your app will be available at:"
echo "   • https://reeledai.com"
echo "   • https://www.reeledai.com"
echo "   • https://app.reeledai.com (already working)"
echo ""
echo "🔍 Verify with:"
echo "   nslookup www.reeledai.com"
echo "   nslookup reeledai.com"
echo "   curl -I https://reeledai.com"










